### ISSUE TITLE
Error when using uint8_t as action parameter

### ISSUE THREAD

**Issue by mgravitt** [LimeChain/eoslime#14]
Hi - thanks so much for developing EOS lime. It's been great to use. I get an error when I use a uint8_t as an action parameter. It works fine with cleos. Have you seen this before?  

```Error: Number format uint8 [object Object] setconfig.use_delphi action.data transaction.actions
      at validateInt (/Users/max/dev/eoslime/node_modules/fcbuffer/lib/types.js:794:11)
      at Object.fromObject (/Users/max/dev/eoslime/node_modules/fcbuffer/lib/types.js:512:7)
      at Object.fromObject (/Users/max/dev/eoslime/node_modules/fcbuffer/lib/struct.js:151:34)
      at actionDataFromObject (/Users/max/dev/eoslime/node_modules/eosjs/lib/structs.js:754:29)```

Here is how I am calling it - the uint8_t is the last parameter just before from:

```await treasuryContract.setconfig(bitcashfeesAccount.name, 0.0025000000000, 0.2000000000, 
            bitcashTokenAccount.name, eosTokenAccount.name, 0.600000000000, 1, { from: treasuryAccount});```

**Comment by bakasura980** [comment]
Hi @gravitt8460, I have not, but I am going to check it. Unfortunately at the moment, I can answer you as early in 2-3 days

**Comment by bakasura980** [comment]
Hi @gravitt8460, In order to figure out the problem I have created a testing contract -

```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
using namespace eosio;

class hello : public eosio::contract
{
public:
    using contract::contract;

    [[eosio::action]] void hi(name user, uint8_t param) {
        print("Hello, ", name{user});
    }
};

EOSIO_DISPATCH(hello, (hi))
```

And try:

```
it.only('Should say hi with uint8_t', async () => {
        let account = await eoslime.Account.createRandom();
      
        helloContract = await eoslime.CleanDeployer.deploy(HELLO_WASM_PATH, HELLO_ABI_PATH);
        await helloContract.hi(account.name, 1, { from: account });
}
```

This test pass. Could you check your contract code. If it is okay, could you provide me the contract code in order to try it and to see if the problem comes from eoslime.

**Comment by bakasura980** [comment]
Hi @gravitt8460 , did you manage to solve the problem ?

**Comment by mgravitt** [comment]
I haven’t gotten back to it yet. I will try this week or close it out. It must be something else wrong on my side. I will integrate your example to my code. Thank you!!
