### ISSUE TITLE
Issues passing time_point object to action

### ISSUE THREAD

**Issue by mgravitt** [LimeChain/eoslime#23]
Hi, I have an action that accepts a "time_point" type as a parameter. I am running into a few issues with how eoslime is attempting to call the action. Here is the ABI:

```
 {
            "name": "newround",
            "base": "",
            "fields": [
                {
                    "name": "round_manager",
                    "type": "name"
                },
                {
                    "name": "term_id",
                    "type": "uint64"
                },
                {
                    "name": "round_start",
                    "type": "time_point"
                }
            ]
        },
```

I initially got errors within:
```eoslime/node_modules/fcbuffer/lib/types.js-- validateInt```

Then, I commented that out and now I receive this error:
```
Error: interior hyphen newround.round_start = "2019-07-21T22:07:00.781Z" action.data = {"round_manager":"l522d54b44f3","term_id":0,"round_start":"2019-07-21T22:07:00.781Z"} transaction.actions = [{"account":"l41a55d3eccb","name":"newround","authorization":[{"actor":"l41a55d3eccb","permission":"active"}],"data":{"round_manager":"l522d54b44f3","term_id":0,"round_start":"2019-07-21T22:07:00.781Z"}}]
      at Function.fromString (/Users/max/dev/eoslime/node_modules/long/dist/long.js:261:19)
      at ByteBuffer.module.exports.ByteBufferPrototype.writeInt64 (/Users/max/dev/eoslime/node_modules/bytebuffer/dist/bytebuffer-node.js:1040:34)
      at Object.appendByteBuffer (/Users/max/dev/eoslime/node_modules/fcbuffer/lib/types.js:509:42)
      at Object.appendByteBuffer (/Users/max/dev/eoslime/node_modules/fcbuffer/lib/struct.js:110:20)
      at actionDataAppendByteBuffer (/Users/max/dev/eoslime/node_modules/eosjs/lib/structs.js:730:13)
```

**Comment by bakasura980** [comment]
Hey @gravitt8460 I am going to look at your error in next 4-5 days

**Comment by bakasura980** [comment]
Hey @gravitt8460, I have wrote a test contract: 

```#include <eosio/eosio.hpp>
#include <string>

namespace tests
{
using namespace eosio;
using std::string;

CONTRACT test : public contract
{
    using contract::contract;

public:
    test(name receiver, name code, datastream<const char *> ds) : contract(receiver, code, ds)
    {
    }

    ACTION testtime(eosio::time_point time_input) {}
};

EOSIO_DISPATCH(test, (testtime));
} // namespace tests
```
My tests are such:

```
const eoslime = require('eoslime').init();

const ABI_PATH = './test.abi';
const WASM_PATH = './test.wasm';

(async () => {
    const contract = await eoslime.CleanDeployer.deploy(WASM_PATH, ABI_PATH);

    try {
        // Always fails
        await contract.testtime('2019-07-21T22:07:00.781Z')
    } catch (error) {
        console.log(error)
    }

    // Always pass
    const now = Date.now();
    await contract.testtime(now)
})()
```

eosio::time_point is uint actually, but you provide string. EOSLIME does not handle type conversion behind the scene. This is more like a feature request ?

**Comment by mgravitt** [comment]
I see. That makes sense. Thanks

**Comment by bakasura980** [comment]
Glad to help you @gravitt8460. Could you provide me some feedback about how you feel eoslime. Is it enough intuitive and flexible for testing. Is the documentation enough simple to follow. Is there something we could improve as function names, simplicity and etc. Also what is missing for you at this point? I would be very happy and very thankful if you share your thoughts. Be honest and feel free to answer at lyubo@limechain.tech
