### ISSUE TITLE
Error: Cannot find module 'mocha'

### ISSUE THREAD

**Issue by varshadqz** [LimeChain/eoslime#75]
I create the directory in which I run,
``` npm install eoslime ```
It installed. After this,
I tried

```
eoslime init
```
It gives the following error:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'mocha'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/eoslime/cli-commands/commands/test/specific/test-frameworks/mocha/index.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I tried to install mocha, 
`npm install mocha`
It fails.
I tried to uninstall and install again **eoslime** and **mocha** but not working. Please help.

**Comment by varshadqz** [comment]
Installed Mocha using ``` sudo apt install mocha ``` and ```  sudo chown -R 1000:1000 "/home/eosnode/.npm" ```. Resolves errors and run.
