### ISSUE TITLE
how can i pass extended_asset parameter to the contract action

### ISSUE THREAD

**Issue by enginterzi** [LimeChain/eoslime#82]
Here is an example.
the extended asset types {"contract":"tethertether","quantity":"2.5000 USDT"} 

await contract.actions.addcurrency([
        "EOS-USDT" ,1, {contract:"tethertether",quantity:"2.5000 USDT"},
         20201231, "2020-12-31T235959", 1,{contract:"eosio.token",quantity:"1.0000 EOS"}]);

here is the error

```
AssertionError [ERR_ASSERTION]: missing amount
    at Object.fromObject (/usr/local/lib/node_modules/eoslime/node_modules/eosjs/lib/structs.js:542:7)
    at Object.fromObject (/usr/local/lib/node_modules/eoslime/node_modules/fcbuffer/lib/struct.js:151:34)
    at actionDataFromObject (/usr/local/lib/node_modules/eoslime/node_modules/eosjs/lib/structs.js:754:29)
    at Object.fromObject (/usr/local/lib/node_modules/eoslime/node_modules/fcbuffer/lib/struct.js:148:15)
    at Object.fromObject (/usr/local/lib/node_modules/eoslime/node_modules/fcbuffer/lib/types.js:387:28)
    at Object.fromObject (/usr/local/lib/node_modules/eoslime/node_modules/fcbuffer/lib/struct.js:151:34)
    at transaction$ (/usr/local/lib/node_modules/eoslime/node_modules/eosjs/lib/write-api.js:800:36)
    at tryCatch (/usr/local/lib/node_modules/eoslime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/eoslime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/eoslime/node_modules/regenerator-runtime/runtime.js:114:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
```

**Comment by enginterzi** [comment]
Since EOSLIME does not handle type conversion behind the scene. 
Here is the right way to deal with enxtended_asset on EOSLIME

```
await contract.actions.addcurrency([
"EOS-USDT" ,1, "2.5000 USDT@tethertether"},
20201231, Date.now(), 1, "1.0000 EOS@eosio.token"]);
```
I hope this helps the people in the future.

**Comment by bakasura980** [comment]
@enginterzi - Just to be sure - You are providing a string and parsing it in the contract or in that way it is being automatically parsed?
